Merged revisions 45027 via svnmerge from https://origsvn.digium.com/svn/asterisk/branches/1.4
........
r45027 | kpfleming | 2006-10-13 10:41:14 -0500 (Fri, 13 Oct 2006) | 2 lines

use a configure script test for PMTU discovery control instead of just assuming it's available on Linux

........


git-svn-id: https://origsvn.digium.com/svn/asterisk/trunk@45029 65c4cc65-6c06-0410-ace0-fbb531ad65f3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14429,6 +14429,93 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
     fi
 
 
+
+    if test "x${PBX_IP_MTU_DISCOVER}" != "x1" -a "${USE_IP_MTU_DISCOVER}" != "no"; then
+	{ echo "$as_me:$LINENO: checking for IP_MTU_DISCOVER in netinet/in.h" >&5
+echo $ECHO_N "checking for IP_MTU_DISCOVER in netinet/in.h... $ECHO_C" >&6; }
+	saved_cppflags="${CPPFLAGS}"
+	if test "x${IP_MTU_DISCOVER_DIR}" != "x"; then
+	    IP_MTU_DISCOVER_INCLUDE= "-I${IP_MTU_DISCOVER_DIR}/include"
+	fi
+	CPPFLAGS="${CPPFLAGS} ${IP_MTU_DISCOVER_INCLUDE}"
+
+	cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netinet/in.h>
+int
+main ()
+{
+int foo = IP_MTU_DISCOVER;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+		PBX_IP_MTU_DISCOVER=1
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IP_MTU_DISCOVER 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IP_MTU_DISCOVER_VERSION
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	       { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+	CPPFLAGS="${saved_cppflags}"
+    fi
+
+
 if test "${ac_cv_header_libkern_OSAtomic_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for libkern/OSAtomic.h" >&5
 echo $ECHO_N "checking for libkern/OSAtomic.h... $ECHO_C" >&6; }
