Make sure that either the main speex library contains preprocess functions or that speexdsp does. If both fail then speex stuff can not be built.
git-svn-id: https://origsvn.digium.com/svn/asterisk/branches/1.4@115327 65c4cc65-6c06-0410-ace0-fbb531ad65f3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -899,6 +899,7 @@ OPENH323_INCDIR
 OPENH323_LIBDIR
 OPENH323_SUFFIX
 OPENH323_BUILD
+PBX_SPEEX_PREPROCESS
 PBX_ZAPTEL_VLDTMF
 PBX_ZAPTEL_TRANSCODE
 EDITLINE_LIB
@@ -29300,6 +29301,419 @@ echo "$as_me: *** without explicitly specifying --with-${SPEEX_OPTION}" >&6;}
 fi
 
 
+# See if the main speex library contains the preprocess functions
+
+if test "${USE_SPEEX_PREPROCESS}" != "no"; then
+   pbxlibdir=""
+   if test "x${SPEEX_PREPROCESS_DIR}" != "x"; then
+      if test -d ${SPEEX_PREPROCESS_DIR}/lib; then
+      	 pbxlibdir="-L${SPEEX_PREPROCESS_DIR}/lib"
+      else
+      	 pbxlibdir="-L${SPEEX_PREPROCESS_DIR}"
+      fi
+   fi
+   { echo "$as_me:$LINENO: checking for speex/speex.h in -lspeex_preprocess_ctl" >&5
+echo $ECHO_N "checking for speex/speex.h in -lspeex_preprocess_ctl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_speex_preprocess_ctl_speex_speex_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspeex_preprocess_ctl ${pbxlibdir}  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char speex/speex.h ();
+int
+main ()
+{
+return speex/speex.h ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_speex_preprocess_ctl_speex_speex_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_speex_preprocess_ctl_speex_speex_h=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_speex_preprocess_ctl_speex_speex_h" >&5
+echo "${ECHO_T}$ac_cv_lib_speex_preprocess_ctl_speex_speex_h" >&6; }
+if test $ac_cv_lib_speex_preprocess_ctl_speex_speex_h = yes; then
+  AST_SPEEX_PREPROCESS_FOUND=yes
+else
+  AST_SPEEX_PREPROCESS_FOUND=no
+fi
+
+
+   if test "${AST_SPEEX_PREPROCESS_FOUND}" = "yes"; then
+      SPEEX_PREPROCESS_LIB="-lspeex_preprocess_ctl "
+      SPEEX_PREPROCESS_HEADER_FOUND="1"
+      if test "x${SPEEX_PREPROCESS_DIR}" != "x"; then
+         SPEEX_PREPROCESS_LIB="${pbxlibdir} ${SPEEX_PREPROCESS_LIB}"
+	 SPEEX_PREPROCESS_INCLUDE="-I${SPEEX_PREPROCESS_DIR}/include"
+	 saved_cppflags="${CPPFLAGS}"
+	 CPPFLAGS="${CPPFLAGS} -I${SPEEX_PREPROCESS_DIR}/include"
+	 if test "x-lm" != "x" ; then
+	    as_ac_Header=`echo "ac_cv_header_${SPEEX_PREPROCESS_DIR}/include/-lm" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for ${SPEEX_PREPROCESS_DIR}/include/-lm" >&5
+echo $ECHO_N "checking for ${SPEEX_PREPROCESS_DIR}/include/-lm... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking ${SPEEX_PREPROCESS_DIR}/include/-lm usability" >&5
+echo $ECHO_N "checking ${SPEEX_PREPROCESS_DIR}/include/-lm usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <${SPEEX_PREPROCESS_DIR}/include/-lm>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking ${SPEEX_PREPROCESS_DIR}/include/-lm presence" >&5
+echo $ECHO_N "checking ${SPEEX_PREPROCESS_DIR}/include/-lm presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <${SPEEX_PREPROCESS_DIR}/include/-lm>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: present but cannot be compiled" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: ${SPEEX_PREPROCESS_DIR}/include/-lm: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------- ##
+## Report this to www.asterisk.org ##
+## ------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for ${SPEEX_PREPROCESS_DIR}/include/-lm" >&5
+echo $ECHO_N "checking for ${SPEEX_PREPROCESS_DIR}/include/-lm... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  SPEEX_PREPROCESS_HEADER_FOUND=1
+else
+  SPEEX_PREPROCESS_HEADER_FOUND=0
+fi
+
+
+	 fi
+	 CPPFLAGS="${saved_cppflags}"
+      else
+	 if test "x-lm" != "x" ; then
+            if test "${ac_cv_header__lm+set}" = set; then
+  { echo "$as_me:$LINENO: checking for -lm" >&5
+echo $ECHO_N "checking for -lm... $ECHO_C" >&6; }
+if test "${ac_cv_header__lm+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header__lm" >&5
+echo "${ECHO_T}$ac_cv_header__lm" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking -lm usability" >&5
+echo $ECHO_N "checking -lm usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <-lm>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking -lm presence" >&5
+echo $ECHO_N "checking -lm presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <-lm>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: -lm: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: -lm: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: -lm: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: -lm: present but cannot be compiled" >&5
+echo "$as_me: WARNING: -lm: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: -lm:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: -lm: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: -lm:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: -lm: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: -lm: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: -lm: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------- ##
+## Report this to www.asterisk.org ##
+## ------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for -lm" >&5
+echo $ECHO_N "checking for -lm... $ECHO_C" >&6; }
+if test "${ac_cv_header__lm+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__lm=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header__lm" >&5
+echo "${ECHO_T}$ac_cv_header__lm" >&6; }
+
+fi
+if test $ac_cv_header__lm = yes; then
+  SPEEX_PREPROCESS_HEADER_FOUND=1
+else
+  SPEEX_PREPROCESS_HEADER_FOUND=0
+fi
+
+
+	 fi
+      fi
+      if test "x${SPEEX_PREPROCESS_HEADER_FOUND}" = "x0" ; then
+         if test -n "${SPEEX_PREPROCESS_MANDATORY}" ;
+         then
+            { echo "$as_me:$LINENO: ***" >&5
+echo "$as_me: ***" >&6;}
+            { echo "$as_me:$LINENO: *** It appears that you do not have the speex_preprocess_ctl development package installed." >&5
+echo "$as_me: *** It appears that you do not have the speex_preprocess_ctl development package installed." >&6;}
+            { echo "$as_me:$LINENO: *** Please install it to include ${SPEEX_PREPROCESS_DESCRIP} support, or re-run configure" >&5
+echo "$as_me: *** Please install it to include ${SPEEX_PREPROCESS_DESCRIP} support, or re-run configure" >&6;}
+            { echo "$as_me:$LINENO: *** without explicitly specifying --with-${SPEEX_PREPROCESS_OPTION}" >&5
+echo "$as_me: *** without explicitly specifying --with-${SPEEX_PREPROCESS_OPTION}" >&6;}
+            exit 1
+         fi
+         SPEEX_PREPROCESS_LIB=""
+         SPEEX_PREPROCESS_INCLUDE=""
+         PBX_SPEEX_PREPROCESS=0
+      else
+         PBX_SPEEX_PREPROCESS=1
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_SPEEX_PREPROCESS 1
+_ACEOF
+
+      fi
+   elif test -n "${SPEEX_PREPROCESS_MANDATORY}";
+   then
+      { echo "$as_me:$LINENO: ***" >&5
+echo "$as_me: ***" >&6;}
+      { echo "$as_me:$LINENO: *** The ${SPEEX_PREPROCESS_DESCRIP} installation on this system appears to be broken." >&5
+echo "$as_me: *** The ${SPEEX_PREPROCESS_DESCRIP} installation on this system appears to be broken." >&6;}
+      { echo "$as_me:$LINENO: *** Either correct the installation, or run configure" >&5
+echo "$as_me: *** Either correct the installation, or run configure" >&6;}
+      { echo "$as_me:$LINENO: *** without explicitly specifying --with-${SPEEX_PREPROCESS_OPTION}" >&5
+echo "$as_me: *** without explicitly specifying --with-${SPEEX_PREPROCESS_OPTION}" >&6;}
+      exit 1
+   fi
+fi
+
+if test "${PBX_SPEEX_PREPROCESS}" = 1; then
+   PBX_SPEEX_PREPROCESS=1
+fi
+
 
 if test "${USE_SPEEXDSP}" != "no"; then
    pbxlibdir=""
@@ -29707,6 +30121,11 @@ echo "$as_me: *** without explicitly specifying --with-${SPEEXDSP_OPTION}" >&6;}
       exit 1
    fi
 fi
+
+if test "${PBX_SPEEXDSP}" = 1; then
+   PBX_SPEEX_PREPROCESS=1
+fi
+
 
 
 
@@ -35910,6 +36329,7 @@ OPENH323_INCDIR!$OPENH323_INCDIR$ac_delim
 OPENH323_LIBDIR!$OPENH323_LIBDIR$ac_delim
 OPENH323_SUFFIX!$OPENH323_SUFFIX$ac_delim
 OPENH323_BUILD!$OPENH323_BUILD$ac_delim
+PBX_SPEEX_PREPROCESS!$PBX_SPEEX_PREPROCESS$ac_delim
 PBX_ZAPTEL_VLDTMF!$PBX_ZAPTEL_VLDTMF$ac_delim
 PBX_ZAPTEL_TRANSCODE!$PBX_ZAPTEL_TRANSCODE$ac_delim
 EDITLINE_LIB!$EDITLINE_LIB$ac_delim
@@ -35920,7 +36340,6 @@ PBX_GTK!$PBX_GTK$ac_delim
 GTK_INCLUDE!$GTK_INCLUDE$ac_delim
 GTK_LIB!$GTK_LIB$ac_delim
 PKGCONFIG!$PKGCONFIG$ac_delim
-PBX_GTK2!$PBX_GTK2$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -35962,13 +36381,14 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PBX_GTK2!$PBX_GTK2$ac_delim
 GTK2_INCLUDE!$GTK2_INCLUDE$ac_delim
 GTK2_LIB!$GTK2_LIB$ac_delim
 CURL_CONFIG!$CURL_CONFIG$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 4; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
