Check for wikiexport.py in PATH and give a useful error message if not found.
git-svn-id: https://origsvn.digium.com/svn/asterisk/branches/1.8@295164 65c4cc65-6c06-0410-ace0-fbb531ad65f3

diff --git a/build_tools/prep_tarball b/build_tools/prep_tarball
--- a/build_tools/prep_tarball
+++ b/build_tools/prep_tarball
@@ -8,6 +8,16 @@
 make -C sounds MENUSELECT_CORE_SOUNDS=CORE-SOUNDS-EN-GSM MENUSELECT_MOH=MOH-OPSOUND-WAV WGET=wget DOWNLOAD=wget all
 make AWK=awk GREP=grep menuselect-tree
 
+if ! which wiikiexport.py 2>&1 > /dev/null ; then
+	echo
+	echo "wikiexport.py not found in \${PATH}."
+	echo
+	echo "Please add repotools into PATH."
+	echo "    $ svn co http://svn.asterisk.org/svn/repotools"
+	echo
+	exit 1
+fi
+
 cd doc
 echo "Exporting Asterisk wiki to a PDF (this will take a minute) ..."
 wikiexport.py
