Check for pdftotext and give a useful error if not found.
git-svn-id: https://origsvn.digium.com/svn/asterisk/branches/1.8@295278 65c4cc65-6c06-0410-ace0-fbb531ad65f3

diff --git a/build_tools/prep_tarball b/build_tools/prep_tarball
--- a/build_tools/prep_tarball
+++ b/build_tools/prep_tarball
@@ -18,6 +18,15 @@ if ! which wikiexport.py 2>&1 > /dev/null ; then
 	exit 1
 fi
 
+if ! which pdftotext 2>&1 > /dev/null ; then
+	echo
+	echo "pdftotext not found.  Please install it."
+	echo
+	echo "On Debian/Ubuntu/Fedora/CentOS, install the poppler-utils package."
+	echo
+	exit 1
+fi
+
 cd doc
 echo "Exporting Asterisk wiki to a PDF (this will take a minute) ..."
 wikiexport.py
